name: CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: install packages
        run: |
          uname -a
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y make gcc libx11-dev ncurses-dev

      - uses: actions/checkout@v4
        with:
          #repository: tsutsui/emacs-18.59-netbsd
          fetch-depth: 200

      - name: configure and make
        run: |
          sudo sh -c "echo 0 > /proc/sys/kernel/randomize_va_space"
          cp src/config.h-linux src/config.h
          make
          sudo make install

  build-linux-i386:
    name: "build-linux (i386 ubuntu)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    container:
      image: i386/ubuntu:latest
      options: --privileged

    steps:
      - name: Prepare packages
        run: |
          uname -a
          apt update
          apt upgrade -y
          apt install -y make gcc libx11-dev ncurses-dev

      - uses: actions/checkout@v1
        with:
          #repository: tsutsui/emacs-18.59-netbsd
          fetch-depth: 200

      - name: Run build process
        run: |
          sysctl kernel.randomize_va_space=0
          cp src/config.h-linux src/config.h
          make
          make install

  build-linux-arm:
    name: "build-linux (ubuntu armv7)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Run build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: arm32v7/ubuntu:latest
          options: |
            --platform linux/arm/v7
            --volume ${{ github.workspace }}:/build
            --workdir /build
          run: |
            uname -a
            apt update
            apt upgrade -y
            apt install -y make gcc libx11-dev ncurses-dev
            cp src/config.h-linux src/config.h
            make
            make install

  build-linux-aarch64:
    name: "build-linux (ubuntu aarch64)"
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - uses: actions/checkout@v4
        with:
          #repository: tsutsui/emacs-18.59-netbsd
          fetch-depth: 200

      - name: Run build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            --volume ${{ github.workspace }}:/build
            --workdir /build
          run: |
            uname -a
            sudo apt update
            sudo apt upgrade -y
            sudo apt install -y make gcc libx11-dev ncurses-dev
            cp src/config.h-linux src/config.h
            make
            sudo make install

  build-netbsd:
    name: "build-netbsd (NetBSD/amd64 10.0 with pkgsrc)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install packages and run configure and make (on the NetBSD VM)
        uses: vmactions/netbsd-vm@v1
        with:
          release: "10.0"
          usesh: true
          copyback: false
          # Check https://github.com/NetBSD/pkgsrc/blob/trunk/net/sayaka/Makefile to check dependencies
          prepare: |
            uname -a
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH
            ftp -o - https://cdn.NetBSD.org/pub/NetBSD/NetBSD-`uname -r`/amd64/binary/sets/xbase.tar.xz | tar -C / -zxpf - ./usr/X11R7/bin ./usr/X11R7/include ./usr/X11R7/lib ./usr/X11R7/share
            ftp -o - https://cdn.NetBSD.org/pub/NetBSD/NetBSD-`uname -r`/amd64/binary/sets/xcomp.tar.xz | tar -C / -zxpf - ./usr/X11R7/include ./usr/X11R7/lib ./usr/X11R7/share

          run: |
            PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
            export PATH
            cp src/config.h-netbsd src/config.h
            make
            make install
